/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetovalidaçãodecampos;

/**
 *
 * @author 277111
 */
public class jframePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jframePrincipal
     */
    public jframePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadastroAluno = new javax.swing.JMenuItem();
        jMenuItemControlePresenca = new javax.swing.JMenuItem();
        jMenuItemControleNotas = new javax.swing.JMenuItem();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/shopping-list (1).png"))); // NOI18N
        jMenu1.setText("Formulários");

        jMenuItemCadastroAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/graduate-student-avatar.png"))); // NOI18N
        jMenuItemCadastroAluno.setText("Cadastro de Alunos");
        jMenuItemCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadastroAluno);

        jMenuItemControlePresenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/heartbeat.png"))); // NOI18N
        jMenuItemControlePresenca.setText("Controle de Presença");
        jMenuItemControlePresenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControlePresencaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemControlePresenca);

        jMenuItemControleNotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/writing.png"))); // NOI18N
        jMenuItemControleNotas.setText("Controle de Notas");
        jMenuItemControleNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemControleNotasActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemControleNotas);

        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/about-us.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSobre);

        jMenuItemClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetovalidaçãodecampos/error.png"))); // NOI18N
        jMenuItemClose.setText("SAIR");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemClose);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroAlunoActionPerformed
        // TODO add your handling code here:
        
        new jframeCadastroAlunos().setVisible(true);
        
    }//GEN-LAST:event_jMenuItemCadastroAlunoActionPerformed

    private void jMenuItemControlePresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControlePresencaActionPerformed
        // TODO add your handling code here:
        
        new jFrameControlePresenca().setVisible(true);
    }//GEN-LAST:event_jMenuItemControlePresencaActionPerformed

    private void jMenuItemControleNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemControleNotasActionPerformed
        // TODO add your handling code here:
        
        new jFrameControleNotas().setVisible(true);
    }//GEN-LAST:event_jMenuItemControleNotasActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
        
        new jFrameSobre().setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCadastroAluno;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemControleNotas;
    private javax.swing.JMenuItem jMenuItemControlePresenca;
    private javax.swing.JMenuItem jMenuItemSobre;
    // End of variables declaration//GEN-END:variables
}
